
import {
	atk,
	hp,
	def,
	atk_spd,
	cooldown,
	crit_per,
	dmg_regist,
	crit_regist,
	amplify_buff,
	debuff_regist,
	raspberry,
	chocolate,
	almond,
	walnet,
	peanut,
	caramel,
	hazelnet,
	chococandy,
	kiwi,
	applejelly,
} from"./base-data.js";
console.log("My topping list");

const data_model = [
	{
		id : "1:number",
		kind : "topping name:string",
		level : "12:number",
		"6" : [], 
		"9" : [], 
		"12" : [], 
	}
];
export const my_toppings = [
	{
		id : 1,
		kind : "raspberry",
		level : 12,
		equip : false,
		own : "",
		"6" : [atk_spd, 2.1],
		"9" : [crit_regist, 3.3],
		"12" : [debuff_regist, 1.1],
	},
	{
		id : 2,
		kind : "raspberry",
		level : 12,
		equip : false,
		own : "",
		"6" : [crit_regist, 3.7],
		"9" : [debuff_regist, 1.4],
		"12" : [crit_per, 2.4],
	},
	{
		id : 3,
		kind : "raspberry",
		level : 12,
		equip : false,
		own : "",
		"6" : [crit_regist, 3.8],
		"9" : [debuff_regist, 1.4],
		"12" : [crit_per, 1.3],
	},
	{
		id : 4,
		kind : "raspberry",
		level : 12,
		equip : false,
		own : "",
		"6" : [dmg_regist, 1.4],
		"9" : [crit_regist, 3],
		"12" : [atk, 1.6],
	},
	{
		id : 5,
		kind : "raspberry",
		level : 9,
		equip : false,
		own : "",
		"6" : [cooldown, 1.6],
		"9" : [crit_regist, 3.4],
		"12" : [null, null],
	},
	{
		id : 6,
		kind : "raspberry",
		level : 12,
		equip : true,
		own : "vampire",
		"6" : [crit_regist, 2.5],
		"9" : [cooldown, 1.9],
		"12" : [debuff_regist, 1.5],
	},
	{
		id : 7,
		kind : "raspberry",
		level : 12,
		equip : true,
		own : "espresso",
		"6" : [atk, 2.3],
		"9" : [amplify_buff, 1.2],
		"12" : [atk_spd, 1.5],
	},
	{
		id : 8,
		kind : "raspberry",
		level : 12,
		equip : true,
		own : "espresso",
		"6" : [atk, 3],
		"9" : [dmg_regist, 1.7],
		"12" : [debuff_regist, 1.5],
	},
	{
		id : 9,
		kind : "raspberry",
		level : 12,
		equip : true,
		own : "vampire",
		"6" : [hp, 2.4],
		"9" : [crit_per, 2.7],
		"12" : [atk, 2.7],
	},
	{
		id : 10,
		kind : "raspberry",
		level : 12,
		equip : true,
		own : "vampire",
		"6" : [crit_per, 2.6],
		"9" : [atk, 1.6],
		"12" : [hp, 2.1],
	},
	{
		id : 11,
		kind : "raspberry",
		level : 12,
		equip : true,
		own : "hub",
		"6" : [crit_per, 2.6],
		"9" : [atk, 1.6],
		"12" : [hp, 2.1],
	},
	{
		id : 12,
		kind : "raspberry",
		level : 12,
		equip : true,
		own : "vampire",
		"6" : [cooldown, 1.9],
		"9" : [debuff_regist, 1.1],
		"12" : [crit_per, 2.7],
	},
	{
		id : 13,
		kind : "raspberry",
		level : 12,
		equip : true,
		own : "pomegranate",
		"6" : [cooldown, 1.9],
		"9" : [debuff_regist, 1.5],
		"12" : [amplify_buff, 2],
	},
	{
		id : 14,
		kind : "raspberry",
		level : 12,
		equip : true,
		own : "black raison",
		"6" : [cooldown, 1.8],
		"9" : [atk, 2.5],
		"12" : [crit_regist, 3.7],
	},
	{
		id : 15,
		kind : "raspberry",
		level : 12,
		equip : true,
		own : "pomegranate",
		"6" : [def, 2.3],
		"9" : [debuff_regist, 1.3],
		"12" : [crit_per, 1.2],
	},
	{
		id : 16,
		kind : "raspberry",
		level : 12,
		equip : true,
		own : "festury",
		"6" : [atk, 1.4],
		"9" : [crit_regist, 3.6],
		"12" : [atk_spd, 2.9],
	},
	{
		id : 17,
		kind : "raspberry",
		level : 12,
		equip : true,
		own : "festury",
		"6" : [crit_regist, 2.1],
		"9" : [atk_spd, 2.3],
		"12" : [cooldown, 1.3],
	},
	{
		id : 18,
		kind : "raspberry",
		level : 12,
		equip : true,
		own : "festury",
		"6" : [atk_spd, 2.9],
		"9" : [crit_regist, 5.9],
		"12" : [amplify_buff, 1.2],
	},
	{
		id : 19,
		kind : "raspberry",
		level : 12,
		equip : true,
		own : "hub",
		"6" : [crit_regist, 3.4],
		"9" : [amplify_buff, 1.3],
		"12" : [atk, 1.3],
	},
	{
		id : 20,
		kind : "raspberry",
		level : 12,
		equip : true,
		own : "black raison",
		"6" : [def, 1.5],
		"9" : [dmg_regist, 5.3],
		"12" : [hp, 2.9],
	},
	{
		id : 21,
		kind : "raspberry",
		level : 12,
		equip : true,
		own : "espresso",
		"6" : [cooldown, 2],
		"9" : [def, 1.2],
		"12" : [atk_spd, 1.6],
	},
	{
		id : 22,
		kind : "raspberry",
		level : 12,
		equip : true,
		own : "hub",
		"6" : [dmg_regist, 5.4],
		"9" : [crit_per, 1.4],
		"12" : [amplify_buff, 1.6],
	},
	{
		id : 23,
		kind : "raspberry",
		level : 12,
		equip : true,
		own : "hub",
		"6" : [crit_regist, 3.3],
		"9" : [dmg_regist, 2],
		"12" : [def, 2.2],
	},
	{
		id : 24,
		kind : "raspberry",
		level : 12,
		equip : true,
		own : "black raison",
		"6" : [atk, 2.8],
		"9" : [hp, 1.6],
		"12" : [def, 1.7],
	},
	{
		id : 25,
		kind : "raspberry",
		level : 12,
		equip : true,
		own : "vampire",
		"6" : [dmg_regist, 5.2],
		"9" : [atk, 2.1],
		"12" : [crit_per, 2.7],
	},
	{
		id : 26,
		kind : "raspberry",
		level : 12,
		equip : true,
		own : "hub",
		"6" : [atk, 1.2],
		"9" : [def, 2.9],
		"12" : [dmg_regist, 1.7],
	},
	{
		id : 27,
		kind : "raspberry",
		level : 12,
		equip : true,
		own : "black raison",
		"6" : [atk, 1.9],
		"9" : [dmg_regist, 2.5],
		"12" : [cooldown, 1.5],
	},
	{
		id : 28,
		kind : "raspberry",
		level : 12,
		equip : true,
		own : "black raison",
		"6" : [hp, 3],
		"9" : [dmg_regist, 5.9],
		"12" : [cooldown, 1.8],
	},
	{
		id : 29,
		kind : "raspberry",
		level : 12,
		equip : true,
		own : "pomegranate",
		"6" : [cooldown, 1.4],
		"9" : [hp, 2.2],
		"12" : [debuff_regist, 1.9],
	},
	{
		id : 30,
		kind : "raspberry",
		level : 12,
		equip : true,
		own : "festury",
		"6" : [amplify_buff, 1.5],
		"9" : [dmg_regist, 4.4],
		"12" : [atk_spd, 2.2],
	},
	{
		id : 31,
		kind : "raspberry",
		level : 12,
		equip : true,
		own : "espresso",
		"6" : [crit_regist, 3.8],
		"9" : [amplify_buff, 1.9],
		"12" : [atk, 2.1],
	},
	{
		id : 32,
		kind : "raspberry",
		level : 12,
		equip : true,
		own : "espresso",
		"6" : [cooldown, 1.4],
		"9" : [atk_spd, 1.8],
		"12" : [amplify_buff, 1],
	},
	{
		id : 33,
		kind : "raspberry",
		level : 12,
		equip : true,
		own : "festury",
		"6" : [debuff_regist, 1.9],
		"9" : [atk_spd, 2.3],
		"12" : [def, 2.3],
	},
];